### ISSUE TITLE
Add more Alert sounds options

### ISSUE THREAD

**Issue by Binternet** [eladnava/redalert-android#11]
The current sound for alert can cause a heart attack for someone. 
The only reason I use the other red-alert app is that they give an option to choose a sound from a small 4-5 sounds library.

You *must* add more built-in alert sound options that comes with the app itself.

**Comment by eladnava** [comment]
@Binternet RedAlert already comes with built-in sound selection of 17 sounds:
https://github.com/eladnava/redalert-android/tree/master/app/src/main/res/raw

**Comment by eladnava** [comment]
The decision to set `alarm1` as the default is that we prefer that the user hear the alert and treat it as serious rather than ignore the phone making a "delightful" sound and not run for shelter.

The assumption is that people who download RedAlert will set the primary alert regions to their actual locations, therefore, they should react accordingly when `alarm1` sounds playing. The issue stems from people misusing the app and enabling alerts for *all* regions, and then being surprised by the `alarm1` siren.
