### ISSUE TITLE
NOTIFICATION DATA from pushy.me

### ISSUE THREAD

**Issue by itaiguli** [eladnava/redalert-android#16]
How should the NOTIFICATION DATA that comes from pushy.me should look?

Maybe this way? :
```
{
"type": "1234567",      // what is this??
"areas": "עוטף עזה 233"
}
```
Thanks.

**Comment by eladnava** [comment]
Hi @itaiguli ,
IDF has released an official statement on their website that they have decided to block 3rd-party Red Alert apps:
1) [IDF](https://www.idf.il/%D7%90%D7%AA%D7%A8%D7%99%D7%9D/%D7%A4%D7%99%D7%A7%D7%95%D7%93-%D7%94%D7%A2%D7%95%D7%A8%D7%A3/%D7%A9%D7%99%D7%A0%D7%95%D7%99-%D7%91%D7%94%D7%A8%D7%A9%D7%90%D7%95%D7%AA-%D7%94%D7%92%D7%99%D7%A9%D7%94-%D7%9C%D7%A7%D7%95%D7%91%D7%A5-%D7%94%D7%94%D7%AA%D7%A8%D7%A2%D7%95%D7%AA-%D7%91%D7%90%D7%AA%D7%A8-%D7%A4%D7%99%D7%A7%D7%95%D7%93-%D7%94%D7%A2%D7%95%D7%A8%D7%A3/)
2) [Mako](https://www.mako.co.il/news-military/security-q1_2019/Article-3e15a4c24c21861004.htm)
3) [Maariv](https://www.maariv.co.il/news/military/Article-678508)

Continuing operations would be illegal. Therefore I cannot help you further in this matter.

The only possible solution is for Pikud Haoref to permit RedAlert to access the alerts file so that service can be restored. You may wish to contact them so that hopefully they change their mind.

**Comment by eladnava** [comment]
The app is active again! 👍
