### ISSUE TITLE
Why not use the Home front command app?

### ISSUE THREAD

**Issue by FunnyIvri** [eladnava/redalert-android#54]
The home front command app is the official app made and run by home front command that doed the same thing as this app but is official.

Then why does this app need to exist?

**Comment by eladnava** [comment]
Hi @FunnyIvri,
The reason this app exists is because the Home Front Command app isn't perfect. Lately, civilians are reporting significant delays in notification delivery with the official HFC app, and the issue has been published in national news:
[דווקא בימים אלו: דיווחים על בעיות באפליקציה של פיקוד העורף](https://www.israelhayom.co.il/tech/tech-news/article/14756352)
[אפליקציית פיקוד העורף מסכנת חיים? זו התקלה שמתלוננים עליה](https://www.ice.co.il/digital-140/news/article/985699)
[משתמשים מדווחים: עיכובים בהתרעות באפליקציית פיקוד העורף](https://www.ynet.co.il/news/article/bjx3yubz6)

Secondly, the HFC app is by default configured to alert based on your current (GPS) location. However, due to the IDF's GPS interference, this feature is malfunctioning:
[שיבושים ב-GPS: זו הסיבה - וכך יש להגדיר באפליקציית פיקוד העורף](https://www.ynet.co.il/news/article/sywzk11ywt)

Finally, the HFC app is quite limited in terms of configurability. For example, it isn't possible to change the alert sound (there are only two choices), and there are no secondary alerts that can be configured with a different sound altogether.

Therefore, this app exists to provide civilians with a reliable alternative to the malfunctioning and/or limited HFC app. Feel free to use both the official HFC app and this one, for extra protection.
